#!/bin/bash
echo -e "\e[1;35mWelcome To AI Tools!"
echo ""

read -p "Deb Path: " deb
read -p "File Name (No Spaces): " filename
mkdir aitools
7z x $deb 
mv data.tar aitools
7z x aitools/data.tar
mv Applications Payload
zip -r $filename.ipa Payload
rm aitools -rf
rm Payload -rf
